
import { Agent, AgentRole, WorkflowStage, ComicProject } from './types';

export const TRANSLATIONS = {
    en: {
        'app.title': 'Studio AI',
        'dept.strategy': 'Editorial Dept.',
        'dept.writers': "Writers' Room",
        'dept.visuals': 'Art Studio',
        'dept.production': 'Post-Production',
        'role.director': 'Editor-in-Chief (You)',
        'role.planner': 'Lead Editor',
        'role.continuity': 'Continuity Editor',
        'role.scriptwriter': 'Screenwriter',
        'role.censor': 'Compliance Officer',
        'role.translator': 'Localization Specialist',
        'role.designer': 'Character Designer',
        'role.artist': 'Panel Artist',
        'role.typesetter': 'Typesetter & Layout',
        'role.cinematographer': 'Motion Director',
        'role.voice': 'Voice Director',
        'role.publisher': 'Distributor',
        'role.archivist': 'Librarian',
        'sidebar.cloud': 'Cloud Storage',
        'sidebar.online': 'Online',
        'step.strategy': '1. Pitching',
        'step.script': '2. Scripting',
        'step.casting': '3. Model Sheets',
        'step.storyboard': '4. Art & Panels',
        'step.printing': '5. Book Layout',
        'step.motion': '6. Motion Comic',
        'step.publish': '7. Distribution',
        'ui.loading': 'Processing...',
        'ui.waiting': 'Awaiting Direction...',
        'ui.save': 'Save',
        'ui.saving': 'Saving...',
        'ui.saved': 'Saved',
        'ui.cancel': 'Cancel',
        'ui.confirm': 'Confirm',
        'ui.upload': 'Upload',
        'ui.reject': 'Reject',
        'ui.approve': 'Approve',
        'ui.language': 'Language',
        'ui.save_success': 'Saved!',
        'ui.save_error': 'Error',
        'ui.voice': 'Voice',
        'ui.back': 'Back',
        'ui.reviewing': 'Reviewing',
        'ui.add_lang': 'Add Language',
        'ui.translate': 'Translate',
        'ui.resume': 'Resume',
        'ui.start_new': 'New Project',
        'ui.quick_import': 'Import',
        'ui.import_script_btn': 'Import Script',
        'ui.import_config_btn': 'Restore Backup',
        'ui.export_zip_btn': 'Export Backup',
        'ui.empty_slot': 'Empty',
        'ui.last_edited': 'Edited',
        'ui.open_project': 'Open',
        'ui.manuscript_loaded': 'Manuscript Loaded',
        'ui.select_format_hint': 'Select Format',
        'ui.current_chapter': 'Chapter',
        'ui.finished': 'Done',
        'ui.season': 'Season',
        'ui.episode': 'Episode',
        'ui.target_length': 'Length',
        'ui.panels': 'Panels',
        'ui.short': 'Short',
        'ui.max': 'Max',
        'ui.delete_confirm': 'Delete?',
        'ui.new_project_confirm': 'New Project?',
        'ui.load_confirm': 'Load Project?',
        'ui.tasks': 'Task List',
        'ui.add_task': 'Add Task',
        'ui.no_tasks': 'No active tasks for this agent.',
        'planner.title': 'Editorial',
        'planner.desc': 'Strategy & IP',
        'planner.chatTitle': 'Chat',
        'planner.chatPlaceholder': 'Type here...',
        'planner.formTitle': 'Series Bible',
        'planner.finalize': 'Finalize',
        'planner.extracting': 'Extracting...',
        'planner.confirmBtn': 'Confirm',
        'manager.title': "Director's Desk",
        'manager.settings': 'Settings',
        'manager.pipeline': 'Pipeline',
        'manager.logs': 'Logs',
        'manager.theme': 'Premise',
        'manager.lang': 'Master Lang',
        'manager.target_langs': 'Languages',
        'manager.style': 'Art Style',
        'manager.format': 'Format',
        'manager.pub_type': 'Publication Type',
        'manager.select_format': 'Select Pipeline',
        'manager.tone': 'Tone',
        'manager.length': 'Scope',
        'manager.tier': 'Tier',
        'manager.themeplaceholder': 'Idea...',
        'manager.slots': 'Projects',
        'manager.new_project': 'New',
        'manager.load': 'Load',
        'manager.delete': 'Delete',
        'manager.full_slots': 'Full',
        'manager.import_file': 'Import',
        'manager.import_script': 'Script',
        'manager.export_file': 'Export',
        'manager.script_status': 'Status',
        'manager.completed_chapters': 'Archives',
        'writer.visual_desc': 'Visual Description',
        'writer.dialogue': 'Dialogue',
        'writer.generate': 'Generate Script',
        'writer.empty': 'Script area empty. Start generation process.',
        'designer.visual_prompt': 'Visual Prompt',
        'designer.generating': 'Designing...',
        'designer.finalize': 'Finalize Cast',
        'voice.actor': 'Voice Actor',
        'voice.audit': 'Audit Voice',
        'voice.match': 'Good Match',
        'voice.mismatch': 'Potential Mismatch',
        'fmt.short': 'One-Shot',
        'fmt.short.desc': 'Short story.',
        'fmt.series': 'Series',
        'fmt.series.desc': 'Long form.',
        'fmt.episodic': 'Episodic',
        'fmt.episodic.desc': 'Webtoon.',
        'type.comic': 'Comic Book / Manga',
        'type.novel': 'Light Novel / Text',
        'style.western': 'Western',
        'style.manga_bw': 'Manga (B&W)',
        'style.manga_color': 'Manga (Color)',
        'style.anime': 'Anime / Cel Shaded',
        'style.animation_2d': '2D Animation (Cartoon)',
        'style.animation_3d': '3D Animation (CGI)',
        'style.webtoon': 'Webtoon',
        'style.wuxia': 'Wuxia',
        'style.noir': 'Noir',
        'style.cyberpunk': 'Cyberpunk',
        'style.realism': 'Realism',
        'style.photoreal': 'Photorealistic (Cinematic)',
        'style.cultivation': 'Cultivation',
        'style.modern_sol': 'Slice of Life',
        'style.gothic': 'Gothic Horror',
        'style.steampunk': 'Steampunk',
        'style.art_nouveau': 'Fantasy Art Nouveau',
        'tone.standard': 'Standard',
        'tone.humor': 'Humor',
        'tone.dark': 'Dark',
        'tone.action': 'Action',
        'tone.emotional': 'Emotional',
        'tone.educational': 'Educational',
        'action.start_research': 'Start Research',
        'action.approve_script': 'Approve Script',
        'action.approve_art': 'Approve Art',
        'action.start_printing': 'Start Layout/Print',
        'action.finalize_prod': 'Finalize Video',
        'action.finalize_chapter': 'Archive Chapter',
        'action.adapt_script': 'Adapt Script',
        'err.no_panels': 'No panels generated.',
        'err.no_chars': 'No characters defined.',
        'err.no_art': 'Art not generated.',
    },
    vi: {
        'app.title': 'Studio AI',
        'dept.strategy': 'Ban Biên Tập',
        'dept.writers': "Phòng Kịch Bản",
        'dept.visuals': 'Studio Mỹ Thuật',
        'dept.production': 'Hậu Kỳ & Xuất Bản',
        'role.director': 'Tổng Biên Tập (Bạn)',
        'role.planner': 'Biên Tập Viên Chính',
        'role.continuity': 'BTV Logic',
        'role.scriptwriter': 'Biên Kịch',
        'role.censor': 'Kiểm Duyệt',
        'role.translator': 'Biên Dịch Viên',
        'role.designer': 'Thiết Kế Nhân Vật',
        'role.artist': 'Họa Sĩ Phân Cảnh',
        'role.typesetter': 'Chuyên gia Dàn trang (In ấn)',
        'role.cinematographer': 'Đạo Diễn Chuyển Động',
        'role.voice': 'Đạo Diễn Lồng Tiếng',
        'role.publisher': 'Nhà Phát Hành',
        'role.archivist': 'Lưu Trữ Viên',
        'sidebar.cloud': 'Lưu Trữ',
        'sidebar.online': 'Online',
        'step.strategy': '1. Đề cương',
        'step.script': '2. Kịch bản',
        'step.casting': '3. Tạo hình',
        'step.storyboard': '4. Vẽ Tranh',
        'step.printing': '5. Dàn Trang/In',
        'step.motion': '6. Dựng Phim',
        'step.publish': '7. Phát hành',
        'ui.loading': 'Đang xử lý...',
        'ui.waiting': 'Đang chờ...',
        'ui.save': 'Lưu',
        'ui.saving': 'Đang lưu...',
        'ui.saved': 'Đã lưu',
        'ui.cancel': 'Hủy',
        'ui.confirm': 'Đồng ý',
        'ui.upload': 'Tải lên',
        'ui.reject': 'Yêu cầu sửa',
        'ui.approve': 'Duyệt',
        'ui.language': 'Ngôn ngữ',
        'ui.save_success': 'Đã lưu!',
        'ui.save_error': 'Lỗi bộ nhớ',
        'ui.voice': 'Giọng đọc',
        'ui.back': 'Quay lại',
        'ui.reviewing': 'Đang xem',
        'ui.add_lang': 'Thêm Ngôn Ngữ',
        'ui.translate': 'Dịch',
        'ui.resume': 'Tiếp Tục',
        'ui.start_new': 'Dự Án Mới',
        'ui.quick_import': 'Nhập Nhanh',
        'ui.import_script_btn': 'Nhập Script (.txt)',
        'ui.import_config_btn': 'Khôi Phục (.zip)',
        'ui.export_zip_btn': 'Sao Lưu (.zip)',
        'ui.empty_slot': 'Trống',
        'ui.last_edited': 'Sửa lần cuối',
        'ui.open_project': 'Mở',
        'ui.manuscript_loaded': 'Đã Tải Bản Thảo',
        'ui.select_format_hint': 'Chọn định dạng:',
        'ui.current_chapter': 'Chương',
        'ui.finished': 'Hoàn thành',
        'ui.season': 'Mùa',
        'ui.episode': 'Tập',
        'ui.target_length': 'Độ dài',
        'ui.panels': 'Khung',
        'ui.short': 'Ngắn',
        'ui.max': 'Dài',
        'ui.delete_confirm': 'Xóa dự án?',
        'ui.new_project_confirm': 'Tạo mới?',
        'ui.load_confirm': 'Mở dự án?',
        'ui.tasks': 'Việc cần làm',
        'ui.add_task': 'Thêm việc',
        'ui.no_tasks': 'Chưa có đầu việc cho Agent này.',
        'planner.title': 'Họp Ban Biên Tập',
        'planner.desc': 'Chiến lược & Thị trường',
        'planner.chatTitle': 'Thảo luận',
        'planner.chatPlaceholder': 'Nhập ý tưởng...',
        'planner.formTitle': 'Hồ Sơ Tác Phẩm',
        'planner.finalize': 'Chốt Đề Cương',
        'planner.extracting': 'Đang tổng hợp...',
        'planner.confirmBtn': 'DUYỆT & LƯU',
        'manager.title': "Bàn Tổng Biên Tập",
        'manager.settings': 'Cấu Hình',
        'manager.pipeline': 'Tiến Độ',
        'manager.logs': 'Nhật Ký',
        'manager.theme': 'Ý Tưởng / Logline',
        'manager.lang': 'Ngôn ngữ Gốc',
        'manager.target_langs': 'Đa Ngôn Ngữ',
        'manager.style': 'Phong cách Vẽ',
        'manager.format': 'Quy mô',
        'manager.pub_type': 'Loại Ấn Phẩm (Book Type)',
        'manager.select_format': 'Chọn Quy Trình',
        'manager.tone': 'Tông màu',
        'manager.length': 'Độ dài',
        'manager.tier': 'Gói AI',
        'manager.themeplaceholder': 'Nhập tóm tắt...',
        'manager.slots': 'Dự Án',
        'manager.new_project': 'Mới',
        'manager.load': 'Mở',
        'manager.delete': 'Xóa',
        'manager.full_slots': 'Đầy',
        'manager.import_file': 'Nhập',
        'manager.import_script': 'Nhập Script',
        'manager.export_file': 'Xuất',
        'manager.script_status': 'Bản thảo',
        'manager.completed_chapters': 'Lưu Trữ',
        'writer.visual_desc': 'Mô tả hình ảnh',
        'writer.dialogue': 'Thoại',
        'writer.generate': 'Viết Kịch Bản',
        'writer.empty': 'Chưa có kịch bản. Hãy bắt đầu quy trình.',
        'designer.visual_prompt': 'Mô tả ngoại hình',
        'designer.generating': 'Đang thiết kế...',
        'designer.finalize': 'Chốt Diễn Viên',
        'voice.actor': 'Diễn viên lồng tiếng',
        'voice.audit': 'Kiểm tra giọng',
        'voice.match': 'Phù hợp',
        'voice.mismatch': 'Không phù hợp',
        'fmt.short': 'Truyện Ngắn (One-Shot)',
        'fmt.short.desc': 'Câu chuyện ngắn gọn.',
        'fmt.series': 'Dài Kỳ (Series)',
        'fmt.series.desc': 'Cốt truyện phức tạp.',
        'fmt.episodic': 'Webtoon (Dọc)',
        'fmt.episodic.desc': 'Cuộn dọc điện thoại.',
        'type.comic': 'Truyện Tranh (Comic)',
        'type.novel': 'Tiểu Thuyết (Novel)',
        'style.western': 'Âu Mỹ',
        'style.manga_bw': 'Manga (Trắng Đen)',
        'style.manga_color': 'Manga (Màu)',
        'style.anime': 'Anime (Hoạt hình Nhật)',
        'style.animation_2d': 'Hoạt hình 2D (Cartoon)',
        'style.animation_3d': 'Hoạt hình 3D (CGI)',
        'style.webtoon': 'Webtoon (Hàn)',
        'style.wuxia': 'Kiếm Hiệp (Trung)',
        'style.noir': 'Noir (Trinh thám)',
        'style.cyberpunk': 'Cyberpunk',
        'style.realism': 'Thực tế',
        'style.photoreal': 'Ảnh Thực (Điện Ảnh)',
        'style.cultivation': 'Tiên Hiệp',
        'style.modern_sol': 'Đời thường (Việt Nam)',
        'style.gothic': 'Kinh dị Gothic',
        'style.steampunk': 'Steampunk (Hơi nước)',
        'style.art_nouveau': 'Art Nouveau (Tân Nghệ Thuật)',
        'tone.standard': 'Tiêu chuẩn',
        'tone.humor': 'Hài hước',
        'tone.dark': 'U tối',
        'tone.action': 'Hành động',
        'tone.emotional': 'Tình cảm',
        'tone.educational': 'Giáo dục',
        'action.start_research': 'Họp Chiến Lược',
        'action.approve_script': 'Chốt Kịch Bản',
        'action.approve_art': 'Chốt Hình Ảnh',
        'action.start_printing': 'Chuyển qua Dàn Trang (In)',
        'action.finalize_prod': 'Hoàn Thiện Video',
        'action.finalize_chapter': 'Lưu & Tập Tiếp',
        'action.adapt_script': 'Chuyển thể',
        'err.no_panels': 'Chưa có phân cảnh nào.',
        'err.no_chars': 'Chưa có nhân vật nào.',
        'err.no_art': 'Chưa vẽ xong tranh.',
    }
};

export const AGENTS: Record<AgentRole, Agent> = {
  [AgentRole.PROJECT_MANAGER]: {
    id: AgentRole.PROJECT_MANAGER,
    name: 'role.director',
    avatar: 'https://picsum.photos/seed/manager/100/100',
    description: 'Supervises the pipeline.',
    color: 'bg-blue-600',
    department: 'dept.strategy'
  },
  [AgentRole.MARKET_RESEARCHER]: {
    id: AgentRole.MARKET_RESEARCHER,
    name: 'role.planner',
    avatar: 'https://picsum.photos/seed/researcher/100/100',
    description: 'Defines style & audience.',
    color: 'bg-indigo-500',
    department: 'dept.strategy'
  },
  [AgentRole.CONTINUITY_EDITOR]: {
    id: AgentRole.CONTINUITY_EDITOR,
    name: 'role.continuity',
    avatar: 'https://picsum.photos/seed/logic/100/100',
    description: 'Checks logic & plot holes.',
    color: 'bg-teal-600',
    department: 'dept.strategy'
  },
  [AgentRole.SCRIPTWRITER]: {
    id: AgentRole.SCRIPTWRITER,
    name: 'role.scriptwriter',
    avatar: 'https://picsum.photos/seed/writer/100/100',
    description: 'Generates plot & dialogue.',
    color: 'bg-emerald-600',
    department: "dept.writers"
  },
  [AgentRole.CENSOR]: {
    id: AgentRole.CENSOR,
    name: 'role.censor',
    avatar: 'https://picsum.photos/seed/censor/100/100',
    description: 'Checks policy compliance.',
    color: 'bg-red-600',
    department: "dept.writers"
  },
  [AgentRole.TRANSLATOR]: {
    id: AgentRole.TRANSLATOR,
    name: 'role.translator',
    avatar: 'https://picsum.photos/seed/translator/100/100',
    description: 'Localizes script.',
    color: 'bg-cyan-600',
    department: "dept.writers"
  },
  [AgentRole.CHARACTER_DESIGNER]: {
    id: AgentRole.CHARACTER_DESIGNER,
    name: 'role.designer',
    avatar: 'https://picsum.photos/seed/designer/100/100',
    description: 'Visualizes characters.',
    color: 'bg-purple-600',
    department: 'dept.visuals'
  },
  [AgentRole.PANEL_ARTIST]: {
    id: AgentRole.PANEL_ARTIST,
    name: 'role.artist',
    avatar: 'https://picsum.photos/seed/artist/100/100',
    description: 'Draws static panel art.',
    color: 'bg-rose-600',
    department: 'dept.visuals'
  },
  [AgentRole.TYPESETTER]: {
    id: AgentRole.TYPESETTER,
    name: 'role.typesetter',
    avatar: 'https://picsum.photos/seed/printer/100/100',
    description: 'Page layout & lettering.',
    color: 'bg-slate-700',
    department: 'dept.production'
  },
  [AgentRole.VOICE_ACTOR]: {
    id: AgentRole.VOICE_ACTOR,
    name: 'role.voice',
    avatar: 'https://picsum.photos/seed/voice/100/100',
    description: 'Generates speech.',
    color: 'bg-pink-600',
    department: 'dept.production'
  },
  [AgentRole.CINEMATOGRAPHER]: {
    id: AgentRole.CINEMATOGRAPHER,
    name: 'role.cinematographer',
    avatar: 'https://picsum.photos/seed/video/100/100',
    description: 'Animates panels (Veo).',
    color: 'bg-orange-600',
    department: 'dept.production'
  },
  [AgentRole.PUBLISHER]: {
    id: AgentRole.PUBLISHER,
    name: 'role.publisher',
    avatar: 'https://picsum.photos/seed/publisher/100/100',
    description: 'Finalizes release.',
    color: 'bg-amber-600',
    department: 'dept.production'
  },
  [AgentRole.ARCHIVIST]: {
    id: AgentRole.ARCHIVIST,
    name: 'role.archivist',
    avatar: 'https://picsum.photos/seed/archivist/100/100',
    description: 'Stores scripts (Text).',
    color: 'bg-stone-600',
    department: 'dept.production'
  }
};

export const INITIAL_PROJECT_STATE: ComicProject = {
  title: 'Untitled Comic',
  theme: '',
  storyFormat: null,
  publicationType: 'COMIC', // Default
  modelTier: 'STANDARD', 
  totalChapters: '', 
  currentChapter: 1,
  targetPanelCount: 20, 
  originalScript: '', 
  masterLanguage: 'Vietnamese',
  targetLanguages: ['Vietnamese'], 
  activeLanguage: 'Vietnamese',
  marketAnalysis: null,
  researchChatHistory: [], 
  censorReport: '',
  isCensored: false,
  style: 'Japanese Manga (B&W)', 
  language: 'Vietnamese',
  coverImage: undefined,
  characters: [],
  panels: [],
  pages: [],
  agentTasks: [], // NEW
  completedChapters: [],
  workflowStage: WorkflowStage.IDLE,
  logs: []
};
